# Generated by Django 3.2.2 on 2021-05-11 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('careerName', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('workplace', models.CharField(max_length=25)),
                ('imageURL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='GameField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('imageURL', models.URLField()),
            ],
        ),
        # migrations.CreateModel(
        #     name='HomeroomTeacherClass',
        #     fields=[
        #         ('className', models.CharField(max_length=25, primary_key=True, serialize=False)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='User',
        #     fields=[
        #         ('ID', models.CharField(max_length=4, primary_key=True, serialize=False)),
        #         ('adminID', models.CharField(max_length=4, null=True)),
        #         ('studentID', models.CharField(max_length=4, null=True)),
        #         ('parentID', models.CharField(max_length=4, null=True)),
        #         ('teacherID', models.CharField(max_length=4, null=True)),
        #         ('username', models.CharField(max_length=10)),
        #         ('isActive', models.BooleanField()),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Admin',
        #     fields=[
        #         ('ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz.user')),
        #         ('password', models.CharField(max_length=10)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Parent',
        #     fields=[
        #         ('ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz.user')),
        #         ('email', models.EmailField(max_length=254)),
        #         ('password', models.CharField(max_length=10)),
        #         ('name', models.CharField(max_length=50)),
        #         ('age', models.IntegerField()),
        #         ('job', models.CharField(max_length=25)),
        #         ('relation', models.CharField(max_length=10)),
        #         ('salutation', models.CharField(max_length=10)),
        #         ('imageURL', models.URLField()),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Student',
        #     fields=[
        #         ('ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz.user')),
        #         ('email', models.EmailField(max_length=254)),
        #         ('password', models.CharField(max_length=10)),
        #         ('name', models.CharField(max_length=50)),
        #         ('year', models.IntegerField()),
        #         ('interest', models.CharField(max_length=20)),
        #         ('imageURL', models.URLField()),
        #         ('parentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.parent')),
        #         ('studentClass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.homeroomteacherclass')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Teacher',
        #     fields=[
        #         ('ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz.user')),
        #         ('email', models.EmailField(max_length=254)),
        #         ('password', models.CharField(max_length=10)),
        #         ('name', models.CharField(max_length=50)),
        #         ('salutation', models.CharField(max_length=10)),
        #         ('role', models.CharField(max_length=20)),
        #         ('imageURL', models.URLField()),
        #     ],
        # ),
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(max_length=150)),
                ('imageURL', models.URLField()),
                ('points', models.IntegerField()),
                ('difficulty', models.CharField(max_length=6)),
                ('careerMention', models.CharField(max_length=20)),
                ('timeLimit', models.CharField(max_length=30)),
                ('lastEdited', models.DateTimeField()),
                ('fieldID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.gamefield')),
            ],
        ),
        migrations.CreateModel(
            name='GameHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.URLField()),
                ('hintText', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.gamequestion')),
            ],
        ),
        migrations.CreateModel(
            name='GameAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerText', models.CharField(max_length=100)),
                ('imageURL', models.URLField()),
                ('isCorrect', models.BooleanField()),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.gamequestion')),
            ],
        ),
        # migrations.AddField(
        #     model_name='homeroomteacherclass',
        #     name='teacherID',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.teacher'),
        # ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.student')),
                ('avatarID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='quiz.avatarcareer')),
            ],
        ),
        migrations.CreateModel(
            name='FieldPlayerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentPointsEarned', models.IntegerField()),
                ('dateLastPlayed', models.DateTimeField()),
                ('hintsUsedCount', models.IntegerField(default=0)),
                ('timeTaken', models.DurationField()),
                ('totalCorrect', models.IntegerField(default=0)),
                ('countHard', models.IntegerField()),
                ('countHardCorrect', models.IntegerField(default=0)),
                ('countMedium', models.IntegerField()),
                ('countMediumCorrect', models.IntegerField(default=0)),
                ('countEasy', models.IntegerField()),
                ('countEasyCorrect', models.IntegerField(default=0)),
                ('fieldID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.gamefield')),
                ('fieldPlayerID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.player')),
            ],
        ),
    ]
