# Generated by Django 3.2.2 on 2021-05-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='playerID',
            new_name='ID',
        ),
    ]
