# Generated by Django 3.2.2 on 2021-05-20 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_playerid_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatarcareer',
            name='careerName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avatarcareer',
            name='workplace',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='avatarID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='quiz.avatarcareer'),
        ),
    ]
