# Generated by Django 3.2.2 on 2021-05-21 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210521_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatarGender', models.CharField(max_length=6)),
                ('avatarID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.avatar')),
            ],
        ),
        migrations.RemoveField(
            model_name='avatargenderurl',
            name='imageURL',
        ),
        migrations.CreateModel(
            name='AvatarGenderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.URLField()),
                ('avatarGender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.avatargender')),
                ('avatarID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.avatar')),
            ],
        ),
    ]
