# Generated by Django 3.2.2 on 2021-05-21 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20210521_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatarID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='quiz.avatargenderimage'),
        ),
        migrations.DeleteModel(
            name='AvatarGenderURL',
        ),
    ]
