# Generated by Django 3.2.2 on 2021-05-21 14:34

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20210521_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatargenderimage',
            name='avatarGender',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='avatarID', chained_model_field='id', on_delete=django.db.models.deletion.CASCADE, to='quiz.avatargender'),
        ),
    ]
