# Generated by Django 3.2.2 on 2021-05-22 08:34

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_avatargenderimage_avatargender'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarGenderImageFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatarGender', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='avatarID', chained_model_field='avatarID', on_delete=django.db.models.deletion.CASCADE, to='quiz.avatargender')),
                ('avatarID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.avatar')),
                ('imageURL', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='avatarGender', chained_model_field='avatarGender', on_delete=django.db.models.deletion.CASCADE, to='quiz.avatargenderimage')),
            ],
        ),
    ]
