# Generated by Django 3.2.2 on 2021-05-22 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_player_avatarid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='workplace',
        ),
        migrations.CreateModel(
            name='AvatarWorkplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplace', models.CharField(max_length=100)),
                ('avatarID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.avatar')),
            ],
        ),
    ]
