# Generated by Django 3.2.2 on 2021-05-22 09:07

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20210522_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatargenderimagefinal',
            name='workplace',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='avatarID', chained_model_field='avatarID', default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.avatarworkplace'),
        ),
    ]
