# Generated by Django 3.2.2 on 2021-05-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_avatargenderimagefinal_workplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatargender',
            name='avatarGender',
            field=models.CharField(max_length=10),
        ),
    ]
