# Generated by Django 3.2.2 on 2021-05-23 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_alter_player_avatarid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvatarGenderImageFinal',
        ),
    ]
