# Generated by Django 3.2.2 on 2021-06-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_alter_player_avatarid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameanswer',
            name='imageURL',
            field=models.URLField(default='NA'),
        ),
        migrations.AlterField(
            model_name='gamefield',
            name='imageURL',
            field=models.URLField(default='NA'),
        ),
        migrations.AlterField(
            model_name='gamehint',
            name='imageURL',
            field=models.URLField(default='NA'),
        ),
        migrations.AlterField(
            model_name='gamequestion',
            name='imageURL',
            field=models.URLField(default='NA'),
        ),
    ]
