# Generated by Django 3.2.2 on 2021-06-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_auto_20210609_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldplayersession',
            name='dateLastPlayed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gamequestion',
            name='lastEdited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
