# Generated by Django 3.2.2 on 2021-06-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_auto_20210609_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameanswer',
            name='answerText',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='gamefield',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gamehint',
            name='hintText',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='gamequestion',
            name='careerMention',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gamequestion',
            name='questionText',
            field=models.CharField(max_length=500),
        ),
    ]
