# Generated by Django 3.2.2 on 2021-06-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_auto_20210609_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamequestion',
            name='difficulty',
            field=models.CharField(max_length=10),
        ),
    ]
