# Generated by Django 3.2.2 on 2021-06-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_alter_gamequestion_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamefield',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
