# Generated by Django 3.2.2 on 2021-06-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_gamefield_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamefield',
            name='lastEdited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
