# Generated by Django 3.2.2 on 2021-06-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_gamefield_lastedited'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tiada Ikon', max_length=50)),
                ('imageURL', models.FilePathField(default='1-default.png', path='/static/images/quiz_field')),
            ],
        ),
    ]
