# Generated by Django 3.2.2 on 2021-06-11 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_imagefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamefield',
            name='imageURL',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='quiz.imagefield'),
        ),
    ]
