# Generated by Django 3.2.2 on 2021-06-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_alter_gamefield_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=50)),
                ('imageURL', models.FilePathField(default='1-default.png', path='/static/images/quiz_avatar')),
            ],
        ),
    ]
