# Generated by Django 3.2.2 on 2021-06-14 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_imageavatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatargenderimage',
            name='imageURL',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='quiz.imageavatar'),
        ),
        migrations.AlterField(
            model_name='imageavatar',
            name='name',
            field=models.CharField(default='Tiada Ikon', max_length=50),
        ),
    ]
