# Generated by Django 3.2.2 on 2021-08-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_auto_20210614_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamehint',
            name='imageURL',
        ),
        migrations.RemoveField(
            model_name='gamequestion',
            name='careerMention',
        ),
    ]
