# Generated by Django 3.2.2 on 2021-08-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_auto_20210804_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameanswer',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='gamehint',
            name='imageURL',
            field=models.URLField(default='NA'),
        ),
    ]
