# Generated by Django 3.2.2 on 2021-08-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_auto_20210805_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamequestion',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='questionImage',
            field=models.ImageField(blank=True, upload_to='images/admin_questions'),
        ),
    ]
