# Generated by Django 3.2.2 on 2021-08-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_auto_20210806_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamehint',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='gamehint',
            name='hintImage',
            field=models.ImageField(blank=True, upload_to='images/admin_hints'),
        ),
    ]
