# Generated by Django 3.2.2 on 2021-08-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0034_auto_20210806_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameanswer',
            name='isCorrect',
            field=models.BooleanField(default=False),
        ),
    ]
