# Generated by Django 3.2.2 on 2021-08-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0035_alter_gameanswer_iscorrect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameanswer',
            name='answerText',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='gamehint',
            name='hintText',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='gamequestion',
            name='questionText',
            field=models.CharField(max_length=1500),
        ),
    ]
