# Generated by Django 3.2.2 on 2021-08-25 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0036_auto_20210819_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageAvatar',
        ),
    ]
