# Generated by Django 3.2.2 on 2021-09-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0037_delete_imageavatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldplayersession',
            name='countEasy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fieldplayersession',
            name='countHard',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fieldplayersession',
            name='countMedium',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fieldplayersession',
            name='currentPointsEarned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fieldplayersession',
            name='timeTaken',
            field=models.DurationField(default=0),
        ),
    ]
