# Generated by Django 3.2.2 on 2021-09-02 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0038_auto_20210902_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldplayersession',
            name='timeTaken',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
