# Generated by Django 3.2.2 on 2021-05-16 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeroomTeacherClass',
            fields=[
                ('className', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('adminID', models.CharField(max_length=4, null=True)),
                ('studentID', models.CharField(max_length=4, null=True)),
                ('parentID', models.CharField(max_length=4, null=True)),
                ('teacherID', models.CharField(max_length=4, null=True)),
                ('username', models.CharField(max_length=10)),
                ('isActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.user')),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.user')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('job', models.CharField(max_length=25)),
                ('relation', models.CharField(max_length=10)),
                ('salutation', models.CharField(max_length=10)),
                ('imageURL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.user')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('salutation', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=20)),
                ('imageURL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.user')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('interest', models.CharField(max_length=20)),
                ('imageURL', models.URLField()),
                ('parentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.parent')),
                ('studentClass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.homeroomteacherclass')),
            ],
        ),
        migrations.AddField(
            model_name='homeroomteacherclass',
            name='teacherID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.teacher'),
        ),
    ]
