# Generated by Django 3.2.2 on 2021-05-16 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210516_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='nonAdminID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.user'),
        ),
        migrations.AlterField(
            model_name='infodashboardbookmark',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='creatorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to='dashboard.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_by', to='dashboard.user'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_for', to='dashboard.user'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='senderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_by', to='dashboard.user'),
        ),
        migrations.AlterField(
            model_name='report',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='creatorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user'),
        ),
    ]
