# Generated by Django 3.2.2 on 2021-05-24 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210516_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parentID',
            field=models.ForeignKey(default=django.db.models.deletion.SET_NULL, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.parent'),
        ),
    ]
