# Generated by Django 3.2.2 on 2021-06-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_parent_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='age',
            field=models.CharField(default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='parent',
            name='imageURL',
            field=models.URLField(default='NA'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='job',
            field=models.CharField(default='NA', max_length=25),
        ),
        migrations.AlterField(
            model_name='parent',
            name='name',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='parent',
            name='relation',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='parent',
            name='salutation',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='imageURL',
            field=models.URLField(default='NA'),
        ),
        migrations.AlterField(
            model_name='student',
            name='interest',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='imageURL',
            field=models.URLField(default='NA'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salutation',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
