# Generated by Django 3.2.2 on 2021-06-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210607_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='job',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='parent',
            name='name',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='interest',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
