# Generated by Django 3.2.2 on 2021-06-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210607_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='relation',
            field=models.CharField(choices=[('NA', 'NA'), ('Ibu Kandung', 'Ibu Kandung'), ('Bapa Kandung', 'Bapa Kandung'), ('Ibu Tiri', 'Ibu Tiri'), ('Bapa Tiri', 'Bapa Tiri'), ('Ibu Angkat', 'Ibu Angkat'), ('Bapa Angkat', 'Bapa Angkat'), ('Adik-beradik', 'Adik-beradik'), ('Datuk', 'Datuk'), ('Nenek', 'Nenek'), ('Ibu Saudara', 'Ibu Saudara'), ('Bapa Saudara', 'Bapa Saudara'), ('Bukan Ahli Keluarga', 'Bukan Ahli Keluarga')], max_length=30),
        ),
        migrations.AlterField(
            model_name='parent',
            name='salutation',
            field=models.CharField(choices=[('NA', 'NA'), ('Tun', 'Tun'), ('Toh Puan', 'Toh Puan'), ('Tan Sri', 'Tan Sri'), ('Puan Sri', 'Puan Sri'), ('Datuk', 'Datuk'), ('Datin', 'Datin'), ('Tuan Haji', 'Tuan Haji'), ('Puan Hajah', 'Puan Hajah'), ('Encik', 'Encik'), ('Puan', 'Puan'), ('Cik', 'Cik')], max_length=15),
        ),
    ]
