# Generated by Django 3.2.2 on 2021-06-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20210607_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='relation',
            field=models.CharField(choices=[('NA', 'NA'), ('Ibu Kandung', 'Ibu Kandung'), ('Bapa Kandung', 'Bapa Kandung'), ('Ibu Tiri', 'Ibu Tiri'), ('Bapa Tiri', 'Bapa Tiri'), ('Ibu Angkat', 'Ibu Angkat'), ('Bapa Angkat', 'Bapa Angkat'), ('Adik-beradik', 'Adik-beradik'), ('Datuk', 'Datuk'), ('Nenek', 'Nenek'), ('Ibu Saudara', 'Ibu Saudara'), ('Bapa Saudara', 'Bapa Saudara'), ('Bukan Ahli Keluarga', 'Bukan Ahli Keluarga')], default='NA', max_length=30),
        ),
        migrations.AlterField(
            model_name='parent',
            name='salutation',
            field=models.CharField(choices=[('NA', 'NA'), ('Tun', 'Tun'), ('Toh Puan', 'Toh Puan'), ('Tan Sri', 'Tan Sri'), ('Puan Sri', 'Puan Sri'), ('Datuk', 'Datuk'), ('Datin', 'Datin'), ('Tuan Haji', 'Tuan Haji'), ('Puan Hajah', 'Puan Hajah'), ('Encik', 'Encik'), ('Puan', 'Puan'), ('Cik', 'Cik')], default='NA', max_length=15),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('Pengetua', 'Pengetua'), ('Penolong Kanan', 'Penolong Kanan'), ('Guru Bimbingan dan Kaunseling', 'Guru Bimbingan dan Kaunseling'), ('Ketua Panitia', 'Ketua Panitia'), ('Guru Media', 'Guru Media'), ('Guru Data', 'Guru Data'), ('Guru Kelas', 'Guru Kelas'), ('Guru Mata Pelajaran', 'Guru Mata Pelajaran')], default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salutation',
            field=models.CharField(choices=[('NA', 'NA'), ('Tun', 'Tun'), ('Toh Puan', 'Toh Puan'), ('Tan Sri', 'Tan Sri'), ('Puan Sri', 'Puan Sri'), ('Datuk', 'Datuk'), ('Datin', 'Datin'), ('Tuan Haji', 'Tuan Haji'), ('Puan Hajah', 'Puan Hajah'), ('Encik', 'Encik'), ('Puan', 'Puan'), ('Cik', 'Cik')], default='NA', max_length=15),
        ),
    ]
