# Generated by Django 3.2.2 on 2021-06-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20210607_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('NA', 'NA'), ('Pengetua', 'Pengetua'), ('Penolong Kanan', 'Penolong Kanan'), ('Guru Bimbingan dan Kaunseling', 'Guru Bimbingan dan Kaunseling'), ('Ketua Panitia', 'Ketua Panitia'), ('Guru Media', 'Guru Media'), ('Guru Data', 'Guru Data'), ('Guru Kelas', 'Guru Kelas'), ('Guru Mata Pelajaran', 'Guru Mata Pelajaran')], default='NA', max_length=50),
        ),
    ]
