# Generated by Django 3.2.2 on 2021-06-07 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_teacher_homeroomclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='year',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(2021), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
