# Generated by Django 3.2.2 on 2021-11-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_teacher_homeroomclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='parent',
            name='password',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=4096),
        ),
    ]
