# Generated by Django 3.2.2 on 2021-12-15 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_teacher_homeroomclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='dateUpdated',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestion',
            name='timeUpdated',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='dateIssued',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='subjectContent',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='timeIssued',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='suggestiontype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
