# Generated by Django 3.2.2 on 2021-12-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20211215_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='status',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
