# Generated by Django 3.2.2 on 2021-12-17 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_suggestion_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='ReportType',
        ),
    ]
