# Generated by Django 3.2.2 on 2021-12-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20211217_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='name',
            field=models.CharField(default='Tidak Dikemaskini', max_length=100),
        ),
    ]
