# Generated by Django 3.2.2 on 2022-01-02 03:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20211224_2105'),
        ('dashboard', '0027_alter_parent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipientID',
        ),
        migrations.AddField(
            model_name='notification',
            name='blogPostID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_notif_for', to='blog.blogpost'),
        ),
        migrations.AlterField(
            model_name='homeroomteacherclass',
            name='year',
            field=models.IntegerField(default=2022, validators=[django.core.validators.MinValueValidator(2021), django.core.validators.MaxValueValidator(2022)]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='isOpen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=2022, validators=[django.core.validators.MinValueValidator(2021), django.core.validators.MaxValueValidator(2022)]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='year',
            field=models.IntegerField(default=2022, validators=[django.core.validators.MinValueValidator(2021), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
