# Generated by Django 3.2.2 on 2022-01-02 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20211224_2105'),
        ('dashboard', '0028_auto_20220102_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='blogPostCommentID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_notif_for', to='blog.blogpostcomment'),
        ),
    ]
