# Generated by Django 3.2.2 on 2022-01-02 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_notification_blogpostcommentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipientID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_for', to='dashboard.user'),
        ),
    ]
