# Generated by Django 3.2.2 on 2022-01-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20220102_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='suggestionStatus',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
