# Generated by Django 3.2.2 on 2022-01-24 14:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_notification_suggestionstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chatroomID',
        ),
        migrations.RemoveField(
            model_name='message',
            name='dateCreated',
        ),
        migrations.RemoveField(
            model_name='message',
            name='parentMessageID',
        ),
        migrations.RemoveField(
            model_name='message',
            name='timeCreated',
        ),
        migrations.AddField(
            model_name='message',
            name='dateTimeComment',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='bodyText',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='message',
            name='creatorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='dashboard.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_by', to='dashboard.user'),
        ),
        migrations.DeleteModel(
            name='Chatroom',
        ),
    ]
