# Generated by Django 3.2.2 on 2022-01-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_message_isread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='dateTimeComment',
            new_name='dateTimeSent',
        ),
    ]
