# Generated by Django 3.2.2 on 2022-02-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_rename_datetimecomment_message_datetimesent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='bodyText',
            field=models.TextField(),
        ),
    ]
