# Generated by Django 3.2.2 on 2021-05-27 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_parent_age'),
        ('blog', '0002_auto_20210516_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostcomment',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.user'),
        ),
    ]
