# Generated by Django 3.2.2 on 2021-10-26 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpostcomment_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogPostImage', models.ImageField(blank=True, upload_to='images/admin_post_images')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogPostVideo', models.FileField(blank=True, upload_to='images/admin_post_videos')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='show',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='noOfShares',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='noOfViews',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='BlogPostContentFile',
        ),
        migrations.AddField(
            model_name='blogpostvideo',
            name='blogPostID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost'),
        ),
        migrations.AddField(
            model_name='blogpostimage',
            name='blogPostID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost'),
        ),
    ]
