# Generated by Django 3.2.2 on 2021-11-14 13:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcomment',
            name='dateTimeComment',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 14, 13, 52, 14, 705680, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpostbookmark',
            name='dateTimeAdded',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogpostcomment',
            name='parentCommentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.blogpostcomment'),
        ),
    ]
