# Generated by Django 3.2.2 on 2021-11-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20211114_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostcomment',
            name='dateTimeComment',
        ),
    ]
