# Generated by Django 3.2.2 on 2021-11-20 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blogpostcomment_datetimecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcomment',
            name='dateTimeComment',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
