# Generated by Django 3.2.2 on 2021-11-23 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogpostcomment_datetimecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcomment',
            name='childCommentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='childs', to='blog.blogpostcomment'),
        ),
        migrations.AlterField(
            model_name='blogpostcomment',
            name='parentCommentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parents', to='blog.blogpostcomment'),
        ),
    ]
