# Generated by Django 3.2.2 on 2021-11-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20211124_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostviewsuser',
            name='noOfViews',
            field=models.IntegerField(default=0),
        ),
    ]
