# Generated by Django 3.2.2 on 2021-12-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogpostviewsuser_noofviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.CharField(default='Tiada rumusan yang berkenaan bagi artikel ini.', max_length=100),
        ),
    ]
