# Generated by Django 3.2.2 on 2021-12-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20211206_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostImageTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogPostImage', models.ImageField(blank=True, upload_to='images/admin_post_images_temp')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostVideoTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogPostVideo', models.FileField(blank=True, upload_to='images/admin_post_videos_temp')),
            ],
        ),
    ]
