# Generated by Django 3.2.2 on 2021-12-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_blogpostimagetemp_blogpostvideotemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
