# Generated by Django 3.2.2 on 2021-12-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_blogpost_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostvideo',
            name='blogPostID',
        ),
        migrations.DeleteModel(
            name='BlogPostVideoTemp',
        ),
        migrations.DeleteModel(
            name='BlogPostVideo',
        ),
    ]
