# Generated by Django 3.2.4 on 2021-12-06 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20211102_2119'),
        ('pTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(max_length=1500)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pTest.personality')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTestResult',
            fields=[
                ('ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.student')),
                ('personality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pTest.personality')),
            ],
        ),
        migrations.DeleteModel(
            name='pTest',
        ),
    ]
