# Generated by Django 3.2.4 on 2021-12-09 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pTest', '0003_auto_20211208_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPersonalitySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('personalityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pTest.personality')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pTest.student')),
            ],
        ),
    ]
