# Generated by Django 3.2.4 on 2021-12-15 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_suggestion_status'),
        ('pTest', '0004_studentpersonalitysession'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentTester',
        ),
        migrations.AlterField(
            model_name='studentpersonalitysession',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.student'),
        ),
    ]
