# Generated by Django 3.2.4 on 2021-12-18 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pTest', '0005_auto_20211216_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentpersonalitysession',
            old_name='score',
            new_name='currentSectionScore',
        ),
        migrations.AlterField(
            model_name='studentpersonalitysession',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pTest.studenttester'),
        ),
    ]
