# Generated by Django 3.2.4 on 2022-01-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pTest', '0008_questions_questiondesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='personality',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
