# Generated by Django 3.2.4 on 2022-01-31 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20220131_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='admission',
        ),
    ]
