# Generated by Django 3.2.4 on 2022-02-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_course_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bridge',
            new_name='UniCourseBridge',
        ),
        # migrations.RemoveField(
        #     model_name='jobs',
        #     name='course',
        # ),
        # migrations.AlterField(
        #     model_name='jobs',
        #     name='job',
        #     field=models.CharField(max_length=120, null=True),
        # ),
        migrations.AlterField(
            model_name='university',
            name='uni',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
