# Generated by Django 3.2.4 on 2022-02-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20220201_2048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
