# Generated by Django 3.2.4 on 2022-02-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_delete_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=120, null=True)),
                ('personality', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
