# Generated by Django 3.2.4 on 2022-02-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_jobs_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='course_id',
        ),
    ]
