# Generated by Django 3.2.4 on 2022-02-01 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_remove_jobs_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCourseBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.course')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.jobs')),
            ],
        ),
    ]
