# Generated by Django 3.2.4 on 2022-02-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_jobcoursebridge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
