# Generated by Django 3.2.4 on 2022-02-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_alter_course_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='uni',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
