# Generated by Django 3.2.4 on 2022-02-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_alter_course_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='langguage',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
