# Generated by Django 3.2.4 on 2022-02-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0016_alter_course_langguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='personality',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
