# Generated by Django 3.2.4 on 2022-02-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0018_auto_20220205_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='fee',
            field=models.CharField(blank=True, default='N/A', max_length=120),
        ),
        migrations.AlterField(
            model_name='university',
            name='populatin',
            field=models.CharField(blank=True, default='N/A', max_length=120),
        ),
    ]
