# Generated by Django 3.2.4 on 2022-02-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0019_auto_20220205_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='populatin',
            new_name='population',
        ),
    ]
