# Generated by Django 3.2.4 on 2022-02-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0020_rename_populatin_university_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='avgDuration',
            field=models.CharField(blank=True, default='N/A', max_length=120),
        ),
        migrations.AddField(
            model_name='course',
            name='avgFee',
            field=models.CharField(blank=True, default='N/A', max_length=120),
        ),
        migrations.AddField(
            model_name='course',
            name='requirement',
            field=models.CharField(blank=True, default='N/A', max_length=120),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='course',
            name='langguage',
            field=models.CharField(blank=True, default='N/A', max_length=120),
        ),
        migrations.AlterField(
            model_name='course',
            name='studyLevel',
            field=models.CharField(blank=True, default='N/A', max_length=120),
        ),
    ]
