# Generated by Django 3.2.4 on 2022-02-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0022_course_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='unicoursebridge',
            name='linkUni',
            field=models.CharField(blank=True, default='N/A', max_length=120),
        ),
    ]
