# Generated by Django 3.2.4 on 2022-02-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0023_unicoursebridge_linkuni'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='avgEmployement',
            field=models.CharField(blank=True, default='N/A', max_length=120),
        ),
        migrations.AddField(
            model_name='jobs',
            name='avgSalary',
            field=models.CharField(blank=True, default='N/A', max_length=120),
        ),
        migrations.AddField(
            model_name='jobs',
            name='description',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='skills',
            field=models.CharField(blank=True, default='N/A', max_length=120),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='personality',
            field=models.CharField(blank=True, default='N/A', max_length=120),
        ),
    ]
