# Generated by Django 3.2.4 on 2022-02-05 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pTest', '0009_personality_description'),
        ('search', '0024_auto_20220205_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='personality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pTest.personality'),
        ),
    ]
