# Generated by Django 3.2.4 on 2022-02-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0025_alter_jobs_personality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='intStudent',
            field=models.BooleanField(default=False),
        ),
    ]
