# Generated by Django 3.2.4 on 2022-02-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0027_alter_university_uni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='uni',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
